# Worker 名称,与CF中的Worker名称必须一致
name = "luischong"

# 兼容性日期，确保使用最新的 Workers 运行时功能
compatibility_date = "2024-10-04"

# 主入口文件
main = "./build/worker/index.js"

# 静态资源目录
assets = { directory = "./build/client" }

# 启用 Workers 日志
[observability]
enabled = true

[vars]
CF_ACCOUNT_LIST = '''[{
    "account_id":"你的CloudFlare帐户ID",
    "token":"有Workers AI权限的API令牌"
}]'''
API_KEY = "your_api_key_here"
CF_TRANSLATE_MODEL = "@cf/qwen/qwen1.5-14b-chat-awq"
CF_IS_TRANSLATE = "true"
USE_EXTERNAL_API = "false"
EXTERNAL_API = "https://openrouter.ai/api/v1/images/generations"
EXTERNAL_MODEL = "google/gemini-2.5-flash-image"
EXTERNAL_API_KEY = "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"
FLUX_NUM_STEPS = "6"
CUSTOMER_MODEL_MAP = '''{
    "FLUX.1-Schnell-CF":"@cf/black-forest-labs/flux-1-schnell",
    "DS-8-CF":"@cf/lykon/dreamshaper-8-lcm",
    "SD-XL-Bash-CF":"@cf/stabilityai/stable-diffusion-xl-base-1.0",
    "SD-XL-Lightning-CF":"@cf/bytedance/stable-diffusion-xl-lightning"
    "Gemini-2.5-Flash": "google/gemini-2.5-flash-image"
}'''
getme = "测试专用"
